name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  test_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Test with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

