name: Build and Test

on:
  push:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run:   |
              chmod +x ./chromeinstall.sh
                          ./chromeinstall.sh
    - name: Build with Maven
      run: mvn test --file pom.xml
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

